sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t kuhlchris/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true kuhlchris/docker-react npm run test

